### ISSUE TITLE
[FEAT] Magento Coding Standards / PHP Compatibility tests

### ISSUE THREAD

**Issue by ihor-sviziev** [graycoreio/github-actions-magento2#27]
# :bulb: Feature request

## Feature Name

Run Magento Coding Standards on top of my module(s)

## The Desired Behavior

I'd like to have the ability to run the Magento Coding Standards static test for my module from the module' or from the project's repository.
In addition to that, I'd like to select the Coding Standard version.

Also, I would like to have the ability to run PHP compatibility tests.

https://github.com/magento/magento-coding-standard
https://github.com/PHPCompatibility/PHPCompatibility

Note: here are the examples:
https://github.com/extdn/github-actions-m2/tree/master/magento-coding-standard
https://github.com/extdn/github-actions-m2/tree/master/magento-copy-paste-detector
https://github.com/extdn/github-actions-m2/tree/master/magento-mess-detector
https://github.com/extdn/github-actions-m2/tree/master/magento-phpstan
https://github.com/extdn/github-actions-m2/tree/master/php-compatibility

They are based on docker and do not support configuring the standard coding version, for instance.

**TODO**:
- [x] Run PHPCS on top of magento-coding-standard
- [ ] Run PHPCS for PHP compatibility
- [ ] Run PhpStan
- [ ] Run PHPMD
- [ ] Run Copy-Paste detector

## Environment

<pre><code>
Magento version: X.Y.Z 
PHP Version version: X.Y.Z 

Others:

</code></pre>

**Comment by damienwebdev** [comment]
@ihor-sviziev could you outline a potential YAML file you'd like to see for your action? Would you prefer a workflow or an action?

**Comment by damienwebdev** [comment]
Partially fixed by #51

**Comment by ihor-sviziev** [comment]
I just checked - in general looks good.
The only thing is missing for me - ability to add additional phpcs params, for instance ` --ignore='*/js/lib/*'`

**Comment by damienwebdev** [comment]
@ihor-sviziev moving that to a separate issue.

**Comment by damienwebdev** [comment]
Closing in favor of https://github.com/mage-os/github-actions/issues/10
